title: Sen Li's Homepage
page-top-title: Sen Li
page-top-title: Li
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
home-subtitle: Li&ensp;|&ensp;李
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
